import type { Request, Response } from "express"
import { z } from "zod"
import type { Pool } from "pg"
import { buildContentDisposition, type AttachmentService } from "./service"
import type { StreamService } from "../streams"
import { VideoTranscodeJobRepository } from "./video"
import type { StorageProvider } from "../../lib/storage/s3-client"

interface Dependencies {
  attachmentService: AttachmentService
  streamService: StreamService
  storage: StorageProvider
  pool: Pool
}

export function createAttachmentHandlers({ attachmentService, streamService, storage, pool }: Dependencies) {
  return {
    /**
     * Upload a file to the workspace.
     * Files are uploaded to workspace-level (no stream) and attached to a stream when linked to a message.
     * Workspace membership is checked by middleware.
     */
    async upload(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!

      // File was uploaded to S3 by multer-s3 middleware
      const file = req.file
      if (!file || !file.key) {
        return res.status(400).json({ error: "No file provided" })
      }

      // The attachment ID was generated by the upload middleware
      const attachmentId = req.attachmentId!

      const uploadResult = await attachmentService.createForUpload({
        id: attachmentId,
        workspaceId,
        uploadedBy: userId,
        filename: file.originalname,
        mimeType: file.mimetype,
        sizeBytes: file.size,
        storagePath: file.key,
      })

      if (uploadResult.status === "cleanup_failed") {
        return res.status(500).json({
          error: "Attachment quarantined and cleanup failed",
          attachmentId: uploadResult.attachmentId,
        })
      }

      if (uploadResult.status === "blocked") {
        return res.status(400).json({ error: uploadResult.reason })
      }

      res.status(201).json({ attachment: uploadResult.attachment })
    },

    /**
     * Get a presigned download URL for an attachment.
     * For attached files, checks stream membership.
     * For pending files (not yet attached), workspace usership is sufficient.
     */
    async getDownloadUrl(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      const sharingBlockReason = attachmentService.getSharingBlockReason(attachment)
      if (sharingBlockReason) {
        return res.status(403).json({ error: sharingBlockReason })
      }

      // For attached files, verify the user can READ the stream — not just
      // that they're a `stream_members` row. Public channels and inherited
      // thread access were previously blocked here because plain `isMember`
      // missed both. `tryAccess` is the canonical read-access check
      // (visibility + workspace match + thread root inheritance).
      if (attachment.streamId) {
        const accessible = await streamService.tryAccess(attachment.streamId, workspaceId, userId)
        if (!accessible) {
          return res.status(403).json({ error: "Access denied" })
        }
      }

      const parsed = z
        .object({
          download: z.enum(["true", "false"]).optional(),
          variant: z.enum(["raw", "processed", "thumbnail"]).optional(),
        })
        .safeParse(req.query)
      if (!parsed.success) return res.status(400).json({ error: "Invalid query parameters" })
      const { download, variant } = parsed.data

      // For video variants (processed/thumbnail), look up the transcode job
      if (variant === "processed" || variant === "thumbnail") {
        const job = await VideoTranscodeJobRepository.findByAttachmentId(pool, attachmentId)
        const path = variant === "processed" ? job?.processedStoragePath : job?.thumbnailStoragePath
        if (job?.status === "completed" && path) {
          const filename =
            variant === "processed" ? attachment.filename.replace(/\.[^.]+$/, ".mp4") : attachment.filename
          const responseContentDisposition = download === "true" ? buildContentDisposition(filename) : undefined
          const url = await storage.getSignedDownloadUrl(path, { responseContentDisposition })
          return res.json({ url, expiresIn: 900 })
        }
        // Fall through to raw file if variant not available
      }

      const url = await attachmentService.getDownloadUrl(attachment, { download: download === "true" })
      res.json({ url, expiresIn: 900 })
    },

    /**
     * Delete an unattached file.
     * Only the user who uploaded the file can delete it.
     * Attached files cannot be deleted.
     */
    async delete(req: Request, res: Response) {
      const userId = req.user!.id
      const workspaceId = req.workspaceId!
      const { attachmentId } = req.params

      const attachment = await attachmentService.getById(attachmentId)
      if (!attachment || attachment.workspaceId !== workspaceId) {
        return res.status(404).json({ error: "Attachment not found" })
      }

      // Only allow deletion of unattached files
      if (attachment.messageId) {
        return res.status(403).json({ error: "Cannot delete attached files" })
      }

      // Only the uploader can delete their own pending files
      if (attachment.uploadedBy && attachment.uploadedBy !== userId) {
        return res.status(403).json({ error: "Cannot delete files uploaded by other users" })
      }

      await attachmentService.delete(attachmentId)
      res.status(204).send()
    },
  }
}
